-- MySQL Script generated by MySQL Workbench
-- Wed Jul 16 18:14:30 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bd_ipc
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bd_ipc
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_ipc` DEFAULT CHARACTER SET utf8 ;
USE `bd_ipc` ;

-- -----------------------------------------------------
-- Table `bd_ipc`.`aplicaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_ipc`.`aplicaciones` (
  `id_Aplicacion` INT NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_Aplicacion`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `bd_ipc`.`bacterias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_ipc`.`bacterias` (
  `id_Bacteria` INT NOT NULL AUTO_INCREMENT,
  `Nombre_cientifico` VARCHAR(45) NOT NULL,
  `Alias` VARCHAR(45) NOT NULL,
  `Descripcion` VARCHAR(150) NULL DEFAULT NULL,
  `Tipo_Bacteria` VARCHAR(45) NULL,
  PRIMARY KEY (`id_Bacteria`),
  UNIQUE INDEX `Nombre_cientifico` (`Nombre_cientifico` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `bd_ipc`.`ubicaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_ipc`.`ubicaciones` (
  `CP` INT NOT NULL,
  `Estado` VARCHAR(45) NULL DEFAULT NULL,
  `Municipio` VARCHAR(45) NULL DEFAULT NULL,
  `Colonia` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`CP`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `bd_ipc`.`suelo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_ipc`.`suelo` (
  `id_Suelo` INT NOT NULL AUTO_INCREMENT,
  `CP` INT NOT NULL,
  `Nombre_Cientifico` VARCHAR(45) NULL,
  `Descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`id_Suelo`),
  INDEX `CP` (`CP` ASC) VISIBLE,
  CONSTRAINT `suelo_ibfk_1`
    FOREIGN KEY (`CP`)
    REFERENCES `bd_ipc`.`ubicaciones` (`CP`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `bd_ipc`.`bacteriasuelo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_ipc`.`bacteriasuelo` (
  `id_Bacteria` INT NOT NULL,
  `id_Suelo` INT NOT NULL,
  UNIQUE INDEX `id_Bacteria` (`id_Bacteria` ASC, `id_Suelo` ASC) VISIBLE,
  INDEX `id_Suelo` (`id_Suelo` ASC) VISIBLE,
  CONSTRAINT `bacteriasuelo_ibfk_1`
    FOREIGN KEY (`id_Bacteria`)
    REFERENCES `bd_ipc`.`bacterias` (`id_Bacteria`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `bacteriasuelo_ibfk_2`
    FOREIGN KEY (`id_Suelo`)
    REFERENCES `bd_ipc`.`suelo` (`id_Suelo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `bd_ipc`.`catcomponentes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_ipc`.`catcomponentes` (
  `id_Componente` INT NOT NULL AUTO_INCREMENT,
  `Codigo_Componente` VARCHAR(45) NOT NULL,
  `Descripcion` VARCHAR(150) NULL DEFAULT NULL,
  `Foto` LONGBLOB NULL DEFAULT NULL,
  PRIMARY KEY (`id_Componente`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `bd_ipc`.`espacios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_ipc`.`espacios` (
  `id_espacios` INT NOT NULL AUTO_INCREMENT,
  `nombre_espacio` VARCHAR(45) NULL,
  `Foto` VARCHAR(150) NULL,
  `clave_acceso` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_espacios`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_ipc`.`circuito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_ipc`.`circuito` (
  `id_Circuito` INT NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(45) NOT NULL,
  `id_Bluetooth` VARCHAR(45) NULL,
  `id_espacios` INT NOT NULL,
  PRIMARY KEY (`id_Circuito`),
  INDEX `fk_circuito_espacios1_idx` (`id_espacios` ASC) VISIBLE,
  CONSTRAINT `fk_circuito_espacios1`
    FOREIGN KEY (`id_espacios`)
    REFERENCES `bd_ipc`.`espacios` (`id_espacios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `bd_ipc`.`circuitoaplicacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_ipc`.`circuitoaplicacion` (
  `id_Aplicacion` INT NOT NULL,
  `id_Circuito` INT NOT NULL,
  UNIQUE INDEX `id_Aplicacion` (`id_Aplicacion` ASC, `id_Circuito` ASC) VISIBLE,
  INDEX `id_Circuito` (`id_Circuito` ASC) VISIBLE,
  CONSTRAINT `circuitoaplicacion_ibfk_1`
    FOREIGN KEY (`id_Aplicacion`)
    REFERENCES `bd_ipc`.`aplicaciones` (`id_Aplicacion`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `circuitoaplicacion_ibfk_2`
    FOREIGN KEY (`id_Circuito`)
    REFERENCES `bd_ipc`.`circuito` (`id_Circuito`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `bd_ipc`.`circuitocomponentes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_ipc`.`circuitocomponentes` (
  `id_Circuito` INT NOT NULL,
  `id_Componente` INT NOT NULL,
  UNIQUE INDEX `id_Circuito` (`id_Circuito` ASC, `id_Componente` ASC) VISIBLE,
  INDEX `id_Componente` (`id_Componente` ASC) VISIBLE,
  CONSTRAINT `circuitocomponentes_ibfk_1`
    FOREIGN KEY (`id_Circuito`)
    REFERENCES `bd_ipc`.`circuito` (`id_Circuito`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `circuitocomponentes_ibfk_2`
    FOREIGN KEY (`id_Componente`)
    REFERENCES `bd_ipc`.`catcomponentes` (`id_Componente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `bd_ipc`.`plantas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_ipc`.`plantas` (
  `id_Planta` INT NOT NULL AUTO_INCREMENT,
  `Nombre_Cientifico` VARCHAR(45) NOT NULL,
  `Alias` VARCHAR(45) NOT NULL,
  `Foto` VARCHAR(150) NULL,
  `Familia` VARCHAR(45) NULL,
  `Descripcion` VARCHAR(300) NULL,
  `id_espacios` INT NOT NULL,
  PRIMARY KEY (`id_Planta`),
  UNIQUE INDEX `Nombre_Cientifico` (`Nombre_Cientifico` ASC) VISIBLE,
  INDEX `fk_plantas_espacios1_idx` (`id_espacios` ASC) VISIBLE,
  CONSTRAINT `fk_plantas_espacios1`
    FOREIGN KEY (`id_espacios`)
    REFERENCES `bd_ipc`.`espacios` (`id_espacios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `bd_ipc`.`	sarrollo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_ipc`.`etapadesarrollo` (
  `id_Etapa` INT NOT NULL AUTO_INCREMENT,
  `Nombre_Cientifico` VARCHAR(45) NOT NULL,
  ` Alias` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_Etapa`),
  UNIQUE INDEX `Nombre_Cientifico` (`Nombre_Cientifico` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

ALTER TABLE etapadesarrollo CHANGE ` Alias` `Alias` VARCHAR(45) NOT NULL;

-- -----------------------------------------------------
-- Table `bd_ipc`.`origencrianzaplanta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_ipc`.`origencrianzaplanta` (
  `id_OrigenCrianza` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Descripcion` VARCHAR(550) NOT NULL,
  PRIMARY KEY (`id_OrigenCrianza`),
  UNIQUE INDEX `Nombre` (`Nombre` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `bd_ipc`.`plagas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_ipc`.`plagas` (
  `id_Plaga` INT NOT NULL AUTO_INCREMENT,
  `Nombre_Cientifico` VARCHAR(45) NOT NULL,
  `Alias` VARCHAR(45) NULL DEFAULT NULL,
  `Descripcion` VARCHAR(150) NULL DEFAULT NULL,
  `Tratamiento` VARCHAR(150) NULL DEFAULT NULL,
  PRIMARY KEY (`id_Plaga`),
  UNIQUE INDEX `Nombre_Cientifico` (`Nombre_Cientifico` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `bd_ipc`.`plantaindividuo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_ipc`.`plantaindividuo` (
  `id_PlantaIndividuo` INT NOT NULL AUTO_INCREMENT,
  `id_Suelo` INT NOT NULL,
  `id_Planta` INT NOT NULL,
  `id_Etapa` INT NOT NULL,
  `id_OrigenCrianza` INT NOT NULL,
  `plagas_id_Plaga` INT NOT NULL,
  `id_espacios` INT NOT NULL,
  PRIMARY KEY (`id_PlantaIndividuo`),
  INDEX `id_Suelo` (`id_Suelo` ASC) VISIBLE,
  INDEX `id_Planta` (`id_Planta` ASC) VISIBLE,
  INDEX `id_Etapa` (`id_Etapa` ASC) VISIBLE,
  INDEX `id_OrigenCrianza` (`id_OrigenCrianza` ASC) VISIBLE,
  INDEX `fk_plantaindividuo_plagas1_idx` (`plagas_id_Plaga` ASC) VISIBLE,
  INDEX `fk_plantaindividuo_espacios1_idx` (`id_espacios` ASC) VISIBLE,
  CONSTRAINT `plantaindividuo_ibfk_1`
    FOREIGN KEY (`id_Suelo`)
    REFERENCES `bd_ipc`.`suelo` (`id_Suelo`)
    ON UPDATE CASCADE,
  CONSTRAINT `plantaindividuo_ibfk_2`
    FOREIGN KEY (`id_Planta`)
    REFERENCES `bd_ipc`.`plantas` (`id_Planta`)
    ON UPDATE CASCADE,
  CONSTRAINT `plantaindividuo_ibfk_3`
    FOREIGN KEY (`id_Etapa`)
    REFERENCES `bd_ipc`.`etapadesarrollo` (`id_Etapa`)
    ON UPDATE CASCADE,
  CONSTRAINT `plantaindividuo_ibfk_4`
    FOREIGN KEY (`id_OrigenCrianza`)
    REFERENCES `bd_ipc`.`origencrianzaplanta` (`id_OrigenCrianza`)
    ON UPDATE CASCADE,
  CONSTRAINT `fk_plantaindividuo_plagas1`
    FOREIGN KEY (`plagas_id_Plaga`)
    REFERENCES `bd_ipc`.`plagas` (`id_Plaga`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_plantaindividuo_espacios1`
    FOREIGN KEY (`id_espacios`)
    REFERENCES `bd_ipc`.`espacios` (`id_espacios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `bd_ipc`.`ubicacioncircuito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_ipc`.`ubicacioncircuito` (
  `id_Ubicacion` INT NOT NULL AUTO_INCREMENT,
  `CP` INT NOT NULL,
  `Descripcion` VARCHAR(145) NULL DEFAULT NULL,
  PRIMARY KEY (`id_Ubicacion`),
  INDEX `CP` (`CP` ASC) VISIBLE,
  CONSTRAINT `ubicacioncircuito_ibfk_1`
    FOREIGN KEY (`CP`)
    REFERENCES `bd_ipc`.`ubicaciones` (`CP`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `bd_ipc`.`circuitoplanta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_ipc`.`circuitoplanta` (
  `id_Circuito` INT NOT NULL,
  `id_PlantaIndividuo` INT NOT NULL,
  `id_Ubicacion` INT NOT NULL,
  UNIQUE INDEX `id_Circuito` (`id_Circuito` ASC) VISIBLE,
  INDEX `id_PlantaIndividuo` (`id_PlantaIndividuo` ASC) VISIBLE,
  INDEX `id_Ubicacion` (`id_Ubicacion` ASC) VISIBLE,
  CONSTRAINT `circuitoplanta_ibfk_1`
    FOREIGN KEY (`id_Circuito`)
    REFERENCES `bd_ipc`.`circuito` (`id_Circuito`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `circuitoplanta_ibfk_2`
    FOREIGN KEY (`id_PlantaIndividuo`)
    REFERENCES `bd_ipc`.`plantaindividuo` (`id_PlantaIndividuo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `circuitoplanta_ibfk_3`
    FOREIGN KEY (`id_Ubicacion`)
    REFERENCES `bd_ipc`.`ubicacioncircuito` (`id_Ubicacion`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `bd_ipc`.`descomponentecomposta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_ipc`.`descomponentecomposta` (
  `id_ComponenteDeComposta` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Descripción` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id_ComponenteDeComposta`),
  UNIQUE INDEX `Nombre` (`Nombre` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `bd_ipc`.`tipocomposta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_ipc`.`tipocomposta` (
  `id_TipoComposta` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Descripción` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`id_TipoComposta`),
  UNIQUE INDEX `Nombre` (`Nombre` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `bd_ipc`.`composta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_ipc`.`composta` (
  `id_Composta` INT NOT NULL AUTO_INCREMENT,
  `id_TipoComposta` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Descripción` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`id_Composta`),
  UNIQUE INDEX `Nombre` (`Nombre` ASC) VISIBLE,
  INDEX `id_TipoComposta` (`id_TipoComposta` ASC) VISIBLE,
  CONSTRAINT `composta_ibfk_1`
    FOREIGN KEY (`id_TipoComposta`)
    REFERENCES `bd_ipc`.`tipocomposta` (`id_TipoComposta`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `bd_ipc`.`componentecomposta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_ipc`.`componentecomposta` (
  `id_ComponenteDeComposta` INT NOT NULL,
  `id_Composta` INT NOT NULL,
  UNIQUE INDEX `id_ComponenteDeComposta` (`id_ComponenteDeComposta` ASC, `id_Composta` ASC) VISIBLE,
  INDEX `id_Composta` (`id_Composta` ASC) VISIBLE,
  CONSTRAINT `componentecomposta_ibfk_1`
    FOREIGN KEY (`id_ComponenteDeComposta`)
    REFERENCES `bd_ipc`.`descomponentecomposta` (`id_ComponenteDeComposta`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `componentecomposta_ibfk_2`
    FOREIGN KEY (`id_Composta`)
    REFERENCES `bd_ipc`.`composta` (`id_Composta`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `bd_ipc`.`proyectos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_ipc`.`proyectos` (
  `id_Proyecto` INT NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_Proyecto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `bd_ipc`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_ipc`.`usuario` (
  `id_Usuario` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `ApellidoPaterno` VARCHAR(20) NOT NULL,
  `ApellidoMaterno` VARCHAR(20) NOT NULL,
  `Telefono` VARCHAR(15) NOT NULL,
  `CorreoElectronico` VARCHAR(100) NOT NULL,
  `Contrasenia` VARCHAR(128) NOT NULL,
  `Foto` VARCHAR(150) NULL,
  PRIMARY KEY (`id_Usuario`),
  UNIQUE INDEX `CorreoElectronico_UNIQUE` (`CorreoElectronico` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `bd_ipc`.`ctrlcomponentes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_ipc`.`ctrlcomponentes` (
  `id_Identificador` INT NOT NULL AUTO_INCREMENT,
  `id_Proyecto` INT NOT NULL,
  `id_Componente` INT NOT NULL,
  `id_Circuito` INT NULL DEFAULT NULL,
  `id_Usuario` INT NOT NULL,
  `fechaIniResponsable` DATETIME NOT NULL,
  `fechaFinResponsable` DATETIME NOT NULL,
  PRIMARY KEY (`id_Identificador`),
  INDEX `id_Proyecto` (`id_Proyecto` ASC) VISIBLE,
  INDEX `id_Componente` (`id_Componente` ASC) VISIBLE,
  INDEX `id_Circuito` (`id_Circuito` ASC) VISIBLE,
  INDEX `id_Usuario` (`id_Usuario` ASC) VISIBLE,
  CONSTRAINT `ctrlcomponentes_ibfk_1`
    FOREIGN KEY (`id_Proyecto`)
    REFERENCES `bd_ipc`.`proyectos` (`id_Proyecto`)
    ON UPDATE CASCADE,
  CONSTRAINT `ctrlcomponentes_ibfk_2`
    FOREIGN KEY (`id_Componente`)
    REFERENCES `bd_ipc`.`catcomponentes` (`id_Componente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `ctrlcomponentes_ibfk_3`
    FOREIGN KEY (`id_Circuito`)
    REFERENCES `bd_ipc`.`circuito` (`id_Circuito`)
    ON UPDATE CASCADE,
  CONSTRAINT `ctrlcomponentes_ibfk_4`
    FOREIGN KEY (`id_Usuario`)
    REFERENCES `bd_ipc`.`usuario` (`id_Usuario`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `bd_ipc`.`material`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_ipc`.`material` (
  `id_Material` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Descripcion` VARCHAR(550) NULL DEFAULT NULL,
  PRIMARY KEY (`id_Material`),
  UNIQUE INDEX `Nombre` (`Nombre` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `bd_ipc`.`electrodos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_ipc`.`electrodos` (
  `id_Electrodos` INT NOT NULL AUTO_INCREMENT,
  `id_Material` INT NOT NULL,
  `Forma` VARCHAR(45) NOT NULL,
  `Largo` VARCHAR(45) NOT NULL,
  `Ancho` VARCHAR(45) NOT NULL,
  `Calibre_Cable` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_Electrodos`),
  INDEX `id_Material` (`id_Material` ASC) VISIBLE,
  CONSTRAINT `electrodos_ibfk_1`
    FOREIGN KEY (`id_Material`)
    REFERENCES `bd_ipc`.`material` (`id_Material`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `bd_ipc`.`sensadoSuelo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_ipc`.`sensadoSuelo` (
  `id_EnergiaPlanta` INT NOT NULL AUTO_INCREMENT,
  `id_Circuito` INT NOT NULL,
  `fechaSensado` DATETIME NOT NULL,
  `Voltaje` FLOAT NOT NULL,
  `Amperaje` FLOAT NOT NULL,
  `id_Electrodos` INT NOT NULL,
  `id_Suelo` INT NULL DEFAULT NULL,
  `PhSuelo` VARCHAR(45) NULL,
  `HumedadSuelo` FLOAT NULL,
  `id_PlantaIndividuo` INT NULL,
  PRIMARY KEY (`id_EnergiaPlanta`),
  INDEX `id_Circuito` (`id_Circuito` ASC) VISIBLE,
  INDEX `id_Electrodos` (`id_Electrodos` ASC) VISIBLE,
  INDEX `id_Suelo` (`id_Suelo` ASC) VISIBLE,
  INDEX `fk_sensadoSuelo_plantaindividuo1_idx` (`id_PlantaIndividuo` ASC) VISIBLE,
  CONSTRAINT `energiaplanta_ibfk_1`
    FOREIGN KEY (`id_Circuito`)
    REFERENCES `bd_ipc`.`circuito` (`id_Circuito`)
    ON UPDATE CASCADE,
  CONSTRAINT `energiaplanta_ibfk_2`
    FOREIGN KEY (`id_Electrodos`)
    REFERENCES `bd_ipc`.`electrodos` (`id_Electrodos`)
    ON UPDATE CASCADE,
  CONSTRAINT `energiaplanta_ibfk_3`
    FOREIGN KEY (`id_Suelo`)
    REFERENCES `bd_ipc`.`suelo` (`id_Suelo`)
    ON UPDATE CASCADE,
  CONSTRAINT `fk_sensadoSuelo_plantaindividuo1`
    FOREIGN KEY (`id_PlantaIndividuo`)
    REFERENCES `bd_ipc`.`plantaindividuo` (`id_PlantaIndividuo`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `bd_ipc`.`video`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_ipc`.`video` (
  `id_Video` INT NOT NULL AUTO_INCREMENT,
  `Direccion` VARCHAR(150) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_Video`),
  UNIQUE INDEX `Nombre` (`Nombre` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `bd_ipc`.`experimentoproximidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_ipc`.`experimentoproximidad` (
  `id_ExperimentoProximidad` INT NOT NULL AUTO_INCREMENT,
  `Distancia` FLOAT NOT NULL,
  `Fecha_Sensado` DATE NOT NULL,
  `Hora_inicio` DATETIME NOT NULL,
  `Hora_fin` DATETIME NOT NULL,
  `id_PlantaIndividuo` INT NOT NULL,
  `id_Electrodos` INT NOT NULL,
  `id_Circuito` INT NOT NULL,
  `id_Video` INT NOT NULL,
  `id_Usuario` INT NOT NULL,
  PRIMARY KEY (`id_ExperimentoProximidad`),
  INDEX `id_Usuario` (`id_Usuario` ASC) VISIBLE,
  INDEX `id_PlantaIndividuo` (`id_PlantaIndividuo` ASC) VISIBLE,
  INDEX `id_Electrodos` (`id_Electrodos` ASC) VISIBLE,
  INDEX `id_Video` (`id_Video` ASC) VISIBLE,
  INDEX `id_Circuito` (`id_Circuito` ASC) VISIBLE,
  CONSTRAINT `experimentoproximidad_ibfk_1`
    FOREIGN KEY (`id_Usuario`)
    REFERENCES `bd_ipc`.`usuario` (`id_Usuario`)
    ON UPDATE CASCADE,
  CONSTRAINT `experimentoproximidad_ibfk_2`
    FOREIGN KEY (`id_PlantaIndividuo`)
    REFERENCES `bd_ipc`.`plantaindividuo` (`id_PlantaIndividuo`)
    ON UPDATE CASCADE,
  CONSTRAINT `experimentoproximidad_ibfk_3`
    FOREIGN KEY (`id_Electrodos`)
    REFERENCES `bd_ipc`.`electrodos` (`id_Electrodos`)
    ON UPDATE CASCADE,
  CONSTRAINT `experimentoproximidad_ibfk_4`
    FOREIGN KEY (`id_Video`)
    REFERENCES `bd_ipc`.`video` (`id_Video`)
    ON UPDATE CASCADE,
  CONSTRAINT `experimentoproximidad_ibfk_5`
    FOREIGN KEY (`id_Circuito`)
    REFERENCES `bd_ipc`.`circuito` (`id_Circuito`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `bd_ipc`.`tipoestimulacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_ipc`.`tipoestimulacion` (
  `id_TipoEstimulacion` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(20) NOT NULL,
  `Descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_TipoEstimulacion`),
  UNIQUE INDEX `Nombre` (`Nombre` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `bd_ipc`.`partesdeplanta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_ipc`.`partesdeplanta` (
  `id_PartePlanta` INT NOT NULL AUTO_INCREMENT,
  `Nombre_Cientifico` VARCHAR(45) NOT NULL,
  `Alias` VARCHAR(45) NULL DEFAULT NULL,
  `Descripcion` VARCHAR(150) NULL DEFAULT NULL,
  `Foto` VARCHAR(150) NULL,
  PRIMARY KEY (`id_PartePlanta`),
  UNIQUE INDEX `Nombre_Cientifico` (`Nombre_Cientifico` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `bd_ipc`.`experimentotacto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_ipc`.`experimentotacto` (
  `id_ExperimentoTacto` INT NOT NULL AUTO_INCREMENT,
  `id_TipoEstimulacion` INT NOT NULL,
  `id_PartePlanta` INT NOT NULL,
  `Fecha_Sensado` DATE NOT NULL,
  `Hora_inicio` DATETIME NOT NULL,
  `Hora_fin` DATETIME NOT NULL,
  `id_PlantaIndividuo` INT NOT NULL,
  `id_Electrodos` INT NOT NULL,
  `id_Circuito` INT NOT NULL,
  `id_Video` INT NOT NULL,
  `id_Usuario` INT NOT NULL,
  PRIMARY KEY (`id_ExperimentoTacto`),
  INDEX `id_Usuario` (`id_Usuario` ASC) VISIBLE,
  INDEX `id_PlantaIndividuo` (`id_PlantaIndividuo` ASC) VISIBLE,
  INDEX `id_Electrodos` (`id_Electrodos` ASC) VISIBLE,
  INDEX `id_Video` (`id_Video` ASC) VISIBLE,
  INDEX `id_Circuito` (`id_Circuito` ASC) VISIBLE,
  INDEX `id_TipoEstimulacion` (`id_TipoEstimulacion` ASC) VISIBLE,
  INDEX `id_PartePlanta` (`id_PartePlanta` ASC) VISIBLE,
  CONSTRAINT `experimentotacto_ibfk_1`
    FOREIGN KEY (`id_Usuario`)
    REFERENCES `bd_ipc`.`usuario` (`id_Usuario`)
    ON UPDATE CASCADE,
  CONSTRAINT `experimentotacto_ibfk_2`
    FOREIGN KEY (`id_PlantaIndividuo`)
    REFERENCES `bd_ipc`.`plantaindividuo` (`id_PlantaIndividuo`)
    ON UPDATE CASCADE,
  CONSTRAINT `experimentotacto_ibfk_3`
    FOREIGN KEY (`id_Electrodos`)
    REFERENCES `bd_ipc`.`electrodos` (`id_Electrodos`)
    ON UPDATE CASCADE,
  CONSTRAINT `experimentotacto_ibfk_4`
    FOREIGN KEY (`id_Video`)
    REFERENCES `bd_ipc`.`video` (`id_Video`)
    ON UPDATE CASCADE,
  CONSTRAINT `experimentotacto_ibfk_5`
    FOREIGN KEY (`id_Circuito`)
    REFERENCES `bd_ipc`.`circuito` (`id_Circuito`)
    ON UPDATE CASCADE,
  CONSTRAINT `experimentotacto_ibfk_6`
    FOREIGN KEY (`id_TipoEstimulacion`)
    REFERENCES `bd_ipc`.`tipoestimulacion` (`id_TipoEstimulacion`)
    ON UPDATE CASCADE,
  CONSTRAINT `experimentotacto_ibfk_7`
    FOREIGN KEY (`id_PartePlanta`)
    REFERENCES `bd_ipc`.`partesdeplanta` (`id_PartePlanta`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `bd_ipc`.`plantapartes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_ipc`.`plantapartes` (
  `id_PartePlanta` INT NOT NULL,
  `id_Planta` INT NOT NULL,
  UNIQUE INDEX `id_Planta` (`id_Planta` ASC, `id_PartePlanta` ASC) VISIBLE,
  INDEX `id_PartePlanta` (`id_PartePlanta` ASC) VISIBLE,
  CONSTRAINT `plantapartes_ibfk_1`
    FOREIGN KEY (`id_PartePlanta`)
    REFERENCES `bd_ipc`.`partesdeplanta` (`id_PartePlanta`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `plantapartes_ibfk_2`
    FOREIGN KEY (`id_Planta`)
    REFERENCES `bd_ipc`.`plantas` (`id_Planta`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `bd_ipc`.`proyectocomponentes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_ipc`.`proyectocomponentes` (
  `id_Proyecto` INT NOT NULL,
  `id_Componente` INT NOT NULL,
  `Cantidad` INT NOT NULL,
  `Observaciones` VARCHAR(45) NOT NULL,
  UNIQUE INDEX `id_Proyecto` (`id_Proyecto` ASC, `id_Componente` ASC) VISIBLE,
  INDEX `id_Componente` (`id_Componente` ASC) VISIBLE,
  CONSTRAINT `proyectocomponentes_ibfk_1`
    FOREIGN KEY (`id_Componente`)
    REFERENCES `bd_ipc`.`catcomponentes` (`id_Componente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `proyectocomponentes_ibfk_2`
    FOREIGN KEY (`id_Proyecto`)
    REFERENCES `bd_ipc`.`proyectos` (`id_Proyecto`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `bd_ipc`.`sensadoambiental`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_ipc`.`sensadoambiental` (
  `FechaSensado` DATETIME NOT NULL,
  `TempAmbiental` FLOAT NULL DEFAULT NULL,
  `Humedad` FLOAT NULL DEFAULT NULL,
  `Lux` FLOAT NULL DEFAULT NULL,
  `Radiacion` FLOAT NULL DEFAULT NULL,
  `id_Circuito` INT NOT NULL,
  `id_EnergiaPlanta` INT NULL DEFAULT NULL,
  `Luz_Azul` FLOAT NULL,
  `Luz_Blanca` FLOAT NULL,
  `Luz_Roja` FLOAT NULL,
  INDEX `id_EnergiaPlanta` (`id_EnergiaPlanta` ASC) VISIBLE,
  INDEX `id_Circuito` (`id_Circuito` ASC) VISIBLE,
  CONSTRAINT `sensadoambiental_ibfk_1`
    FOREIGN KEY (`id_EnergiaPlanta`)
    REFERENCES `bd_ipc`.`sensadoSuelo` (`id_EnergiaPlanta`)
    ON UPDATE CASCADE,
  CONSTRAINT `sensadoambiental_ibfk_2`
    FOREIGN KEY (`id_Circuito`)
    REFERENCES `bd_ipc`.`circuito` (`id_Circuito`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `bd_ipc`.`sensadocontaminantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_ipc`.`sensadocontaminantes` (
  `id_Circuito` INT NOT NULL,
  `fechaSensado` DATETIME NOT NULL,
  `CO` DECIMAL(5,2) NOT NULL,
  `CO2` DECIMAL(5,2) NOT NULL,
  `O` DECIMAL(5,2) NOT NULL,
  `COVs` DECIMAL(5,2) NOT NULL,
  PRIMARY KEY (`fechaSensado`),
  INDEX `id_Circuito` (`id_Circuito` ASC) VISIBLE,
  CONSTRAINT `sensadocontaminantes_ibfk_1`
    FOREIGN KEY (`id_Circuito`)
    REFERENCES `bd_ipc`.`circuito` (`id_Circuito`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `bd_ipc`.`suelocomposta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_ipc`.`suelocomposta` (
  `id_Suelo` INT NOT NULL,
  `id_Composta` INT NOT NULL,
  UNIQUE INDEX `id_Suelo` (`id_Suelo` ASC, `id_Composta` ASC) VISIBLE,
  INDEX `id_Composta` (`id_Composta` ASC) VISIBLE,
  CONSTRAINT `suelocomposta_ibfk_1`
    FOREIGN KEY (`id_Suelo`)
    REFERENCES `bd_ipc`.`suelo` (`id_Suelo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `suelocomposta_ibfk_2`
    FOREIGN KEY (`id_Composta`)
    REFERENCES `bd_ipc`.`composta` (`id_Composta`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `bd_ipc`.`especies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_ipc`.`especies` (
  `id_especies` INT NOT NULL AUTO_INCREMENT,
  `Nombre_Cientifico` VARCHAR(45) NULL,
  `Alias` VARCHAR(45) NULL,
  `Foto` VARCHAR(150) NULL,
  `Descripcion` VARCHAR(150) NULL,
  `Origen` VARCHAR(45) NULL,
  `id_Planta` INT NOT NULL,
  PRIMARY KEY (`id_especies`),
  INDEX `fk_especies_plantas1_idx` (`id_Planta` ASC) VISIBLE,
  CONSTRAINT `fk_especies_plantas1`
    FOREIGN KEY (`id_Planta`)
    REFERENCES `bd_ipc`.`plantas` (`id_Planta`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_ipc`.`tokens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_ipc`.`tokens` (
  `id_tokens` INT NOT NULL AUTO_INCREMENT,
  `token` VARCHAR(128) NULL,
  `id_Usuario` INT NOT NULL,
  PRIMARY KEY (`id_tokens`),
  INDEX `fk_tokens_usuario1_idx` (`id_Usuario` ASC) VISIBLE,
  CONSTRAINT `fk_tokens_usuario1`
    FOREIGN KEY (`id_Usuario`)
    REFERENCES `bd_ipc`.`usuario` (`id_Usuario`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_ipc`.`espaciosUsuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_ipc`.`espaciosUsuarios` (
  `id_Usuario` INT NOT NULL,
  `id_espacios` INT NOT NULL,
  `isAdmin` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id_Usuario`, `id_espacios`),
  INDEX `fk_espaciosUsuarios_espacios1_idx` (`id_espacios` ASC) VISIBLE,
  CONSTRAINT `fk_espaciosUsuarios_espacios1`
    FOREIGN KEY (`id_espacios`)
    REFERENCES `bd_ipc`.`espacios` (`id_espacios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_espaciosUsuarios_usuario1`
    FOREIGN KEY (`id_Usuario`)
    REFERENCES `bd_ipc`.`usuario` (`id_Usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
