-- MySQL Script generated by MySQL Workbench
-- Thu Oct 9 23:31:44 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bd_ipc
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bd_ipc
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_ipc` DEFAULT CHARACTER SET utf8 ;
USE `bd_ipc` ;

-- -----------------------------------------------------
-- Table `bd_ipc`.`aplicaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_ipc`.`aplicaciones` (
  `id_Aplicacion` INT NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_Aplicacion`)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `bd_ipc`.`bacterias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_ipc`.`bacterias` (
  `id_Bacteria` INT NOT NULL AUTO_INCREMENT,
  `Nombre_cientifico` VARCHAR(45) NOT NULL,
  `Alias` VARCHAR(45) NOT NULL,
  `Descripcion` VARCHAR(150) NULL DEFAULT NULL,
  `Tipo_Bacteria` VARCHAR(45) NULL, 
  PRIMARY KEY (`id_Bacteria`),
  UNIQUE INDEX `Nombre_cientifico` (`Nombre_cientifico` ASC) 
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `bd_ipc`.`ubicaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_ipc`.`ubicaciones` (
  `CP` INT NOT NULL,
  `Estado` VARCHAR(45) NULL DEFAULT NULL,
  `Municipio` VARCHAR(45) NULL DEFAULT NULL,
  `Colonia` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`CP`)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `bd_ipc`.`suelo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_ipc`.`suelo` (
  `id_Suelo` INT NOT NULL AUTO_INCREMENT,
  `CP` INT NOT NULL,
  `Nombre_Cientifico` VARCHAR(45) NULL,
  `Descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`id_Suelo`),
  INDEX `CP` (`CP` ASC), 
  CONSTRAINT `suelo_ibfk_1`
    FOREIGN KEY (`CP`)
    REFERENCES `bd_ipc`.`ubicaciones` (`CP`)
    ON UPDATE CASCADE
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `bd_ipc`.`bacteriasuelo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_ipc`.`bacteriasuelo` (
  `id_Bacteria` INT NOT NULL,
  `id_Suelo` INT NOT NULL,
  UNIQUE INDEX `id_Bacteria` (`id_Bacteria` ASC, `id_Suelo` ASC), 
  INDEX `id_Suelo` (`id_Suelo` ASC), 
  CONSTRAINT `bacteriasuelo_ibfk_1`
    FOREIGN KEY (`id_Bacteria`)
    REFERENCES `bd_ipc`.`bacterias` (`id_Bacteria`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `bacteriasuelo_ibfk_2`
    FOREIGN KEY (`id_Suelo`)
    REFERENCES `bd_ipc`.`suelo` (`id_Suelo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `bd_ipc`.`catcomponentes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_ipc`.`catcomponentes` (
  `id_Componente` INT NOT NULL AUTO_INCREMENT,
  `Codigo_Componente` VARCHAR(45) NOT NULL,
  `Descripcion` VARCHAR(150) NULL DEFAULT NULL,
  `Foto` LONGBLOB NULL DEFAULT NULL,
  PRIMARY KEY (`id_Componente`)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `bd_ipc`.`espacios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_ipc`.`espacios` (
  `id_espacios` INT NOT NULL AUTO_INCREMENT,
  `nombre_espacio` VARCHAR(45) NULL,
  `Foto` VARCHAR(150) NULL,
  `clave_acceso` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_espacios`)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4; 


-- -----------------------------------------------------
-- Table `bd_ipc`.`plantasespacios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_ipc`.`plantasespacios` (
  `id_Planta` INT NOT NULL,
  `id_espacio` INT NOT NULL,
  `cantidad` INT DEFAULT 1,
  PRIMARY KEY (`id_Planta`, `id_espacio`),
  INDEX `fk_plantasespacios_espacios_idx` (`id_espacio` ASC),
  CONSTRAINT `fk_plantasespacios_plantas`
    FOREIGN KEY (`id_Planta`)
    REFERENCES `bd_ipc`.`plantas` (`id_Planta`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_plantasespacios_espacios`
    FOREIGN KEY (`id_espacio`)
    REFERENCES `bd_ipc`.`espacios` (`id_espacios`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `bd_ipc`.`circuito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_ipc`.`circuito` (
  `bluetooth` VARCHAR(45) NOT NULL,        
  `id_tipo_circuito` INT NOT NULL,         
  `id_espacios` INT NOT NULL,
  PRIMARY KEY (`bluetooth`),
  INDEX `fk_circuito_espacios1_idx` (`id_espacios` ASC),
  INDEX `fk_circuito_tipoCircuitos_idx` (`id_tipo_circuito` ASC),
  CONSTRAINT `fk_circuito_espacios1`
    FOREIGN KEY (`id_espacios`)
    REFERENCES `bd_ipc`.`espacios` (`id_espacios`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_circuito_tipoCircuitos`
    FOREIGN KEY (`id_tipo_circuito`)
    REFERENCES `bd_ipc`.`tipoCircuitos` (`id_tipo_circuito`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET=utf8mb4;


-- -----------------------------------------------------
-- Table `bd_ipc`.`tipoCircuitos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_ipc`.`tipoCircuitos` (
  `id_tipo_circuito` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_tipo_circuito`)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `bd_ipc`.`circuitoaplicacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_ipc`.`circuitoaplicacion` (
  `id_Aplicacion` INT NOT NULL,
  `bluetooth` VARCHAR(45) NOT NULL,  
  UNIQUE INDEX `id_Aplicacion` (`id_Aplicacion` ASC, `bluetooth` ASC), 
  INDEX `bluetooth` (`bluetooth` ASC), 
  CONSTRAINT `circuitoaplicacion_ibfk_1`
    FOREIGN KEY (`id_Aplicacion`)
    REFERENCES `bd_ipc`.`aplicaciones` (`id_Aplicacion`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `circuitoaplicacion_ibfk_2`
    FOREIGN KEY (`bluetooth`)
    REFERENCES `bd_ipc`.`circuito` (`bluetooth`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `bd_ipc`.`circuitocomponentes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_ipc`.`circuitocomponentes` (
  `bluetooth` VARCHAR(45) NOT NULL,  -- reemplazo de id_Circuito
  `id_Componente` INT NOT NULL,
  UNIQUE INDEX `id_Circuito` (`bluetooth` ASC, `id_Componente` ASC), 
  INDEX `id_Componente` (`id_Componente` ASC), 
  CONSTRAINT `circuitocomponentes_ibfk_1`
    FOREIGN KEY (`bluetooth`)
    REFERENCES `bd_ipc`.`circuito` (`bluetooth`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `circuitocomponentes_ibfk_2`
    FOREIGN KEY (`id_Componente`)
    REFERENCES `bd_ipc`.`catcomponentes` (`id_Componente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `bd_ipc`.`plantas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_ipc`.`plantas` (
  `id_Planta` INT NOT NULL AUTO_INCREMENT,
  `Nombre_Cientifico` VARCHAR(45) NOT NULL,
  `Alias` VARCHAR(45) NOT NULL,
  `Foto` VARCHAR(150) NULL,
  `Familia` VARCHAR(45) NULL,
  `Descripcion` VARCHAR(300) NULL,
  PRIMARY KEY (`id_Planta`),
  UNIQUE INDEX `Nombre_Cientifico` (`Nombre_Cientifico` ASC)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;



-- -----------------------------------------------------
-- Table `bd_ipc`.`etapadesarrollo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_ipc`.`etapadesarrollo` (
  `id_Etapa` INT NOT NULL AUTO_INCREMENT,
  `Nombre_Cientifico` VARCHAR(45) NOT NULL,
  `Alias` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_Etapa`),
  UNIQUE INDEX `Nombre_Cientifico` (`Nombre_Cientifico` ASC) 
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `bd_ipc`.`origencrianzaplanta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_ipc`.`origencrianzaplanta` (
  `id_OrigenCrianza` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Descripcion` VARCHAR(550) NOT NULL,
  PRIMARY KEY (`id_OrigenCrianza`),
  UNIQUE INDEX `Nombre` (`Nombre` ASC) 
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `bd_ipc`.`plagas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_ipc`.`plagas` (
  `id_Plaga` INT NOT NULL AUTO_INCREMENT,
  `Nombre_Cientifico` VARCHAR(45) NOT NULL,
  `Alias` VARCHAR(45) NULL DEFAULT NULL,
  `Descripcion` VARCHAR(150) NULL DEFAULT NULL,
  `Tratamiento` VARCHAR(150) NULL DEFAULT NULL,
  PRIMARY KEY (`id_Plaga`),
  UNIQUE INDEX `Nombre_Cientifico` (`Nombre_Cientifico` ASC) 
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `bd_ipc`.`plantaindividuo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_ipc`.`plantaindividuo` (
  `id_PlantaIndividuo` INT NOT NULL AUTO_INCREMENT,
  `id_Suelo` INT NOT NULL,
  `id_Planta` INT NOT NULL,
  `id_Etapa` INT NOT NULL,
  `id_OrigenCrianza` INT NOT NULL,
  `plagas_id_Plaga` INT NOT NULL,
  `id_espacios` INT NOT NULL,
  PRIMARY KEY (`id_PlantaIndividuo`),
  INDEX `id_Suelo` (`id_Suelo` ASC), 
  INDEX `id_Planta` (`id_Planta` ASC), 
  INDEX `id_Etapa` (`id_Etapa` ASC), 
  INDEX `id_OrigenCrianza` (`id_OrigenCrianza` ASC), 
  INDEX `fk_plantaindividuo_plagas1_idx` (`plagas_id_Plaga` ASC), 
  INDEX `fk_plantaindividuo_espacios1_idx` (`id_espacios` ASC), 
  CONSTRAINT `plantaindividuo_ibfk_1`
    FOREIGN KEY (`id_Suelo`)
    REFERENCES `bd_ipc`.`suelo` (`id_Suelo`)
    ON UPDATE CASCADE,
  CONSTRAINT `plantaindividuo_ibfk_2`
    FOREIGN KEY (`id_Planta`)
    REFERENCES `bd_ipc`.`plantas` (`id_Planta`)
    ON UPDATE CASCADE,
  CONSTRAINT `plantaindividuo_ibfk_3`
    FOREIGN KEY (`id_Etapa`)
    REFERENCES `bd_ipc`.`etapadesarrollo` (`id_Etapa`)
    ON UPDATE CASCADE,
  CONSTRAINT `plantaindividuo_ibfk_4`
    FOREIGN KEY (`id_OrigenCrianza`)
    REFERENCES `bd_ipc`.`origencrianzaplanta` (`id_OrigenCrianza`)
    ON UPDATE CASCADE,
  CONSTRAINT `fk_plantaindividuo_plagas1`
    FOREIGN KEY (`plagas_id_Plaga`)
    REFERENCES `bd_ipc`.`plagas` (`id_Plaga`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_plantaindividuo_espacios1`
    FOREIGN KEY (`id_espacios`)
    REFERENCES `bd_ipc`.`espacios` (`id_espacios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `bd_ipc`.`ubicacion_espacio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_ipc`.`ubicacion_espacio` (
  `id_Ubicacion` INT NOT NULL AUTO_INCREMENT,
  `CP` INT NOT NULL,
  `Descripcion` VARCHAR(145) NULL DEFAULT NULL,
  `id_espacio` INT NOT NULL,
  PRIMARY KEY (`id_Ubicacion`),
  INDEX `CP` (`CP` ASC), 
  INDEX `id_espacio` (`id_espacio` ASC),
  CONSTRAINT `ubicacion_espacio_ibfk_1`
    FOREIGN KEY (`CP`)
    REFERENCES `bd_ipc`.`ubicaciones` (`CP`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `ubicacion_espacio_ibfk_2`
    FOREIGN KEY (`id_espacio`)
    REFERENCES `bd_ipc`.`espacios` (`id_espacios`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `bd_ipc`.`descomponentecomposta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_ipc`.`descomponentecomposta` (
  `id_ComponenteDeComposta` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Descripción` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id_ComponenteDeComposta`),
  UNIQUE INDEX `Nombre` (`Nombre` ASC) 
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `bd_ipc`.`tipocomposta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_ipc`.`tipocomposta` (
  `id_TipoComposta` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Descripción` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`id_TipoComposta`),
  UNIQUE INDEX `Nombre` (`Nombre` ASC) 
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `bd_ipc`.`composta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_ipc`.`composta` (
  `id_Composta` INT NOT NULL AUTO_INCREMENT,
  `id_TipoComposta` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Descripción` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`id_Composta`),
  UNIQUE INDEX `Nombre` (`Nombre` ASC), 
  INDEX `id_TipoComposta` (`id_TipoComposta` ASC), 
  CONSTRAINT `composta_ibfk_1`
    FOREIGN KEY (`id_TipoComposta`)
    REFERENCES `bd_ipc`.`tipocomposta` (`id_TipoComposta`)
    ON UPDATE CASCADE
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `bd_ipc`.`componentecomposta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_ipc`.`componentecomposta` (
  `id_ComponenteDeComposta` INT NOT NULL,
  `id_Composta` INT NOT NULL,
  UNIQUE INDEX `id_ComponenteDeComposta` (`id_ComponenteDeComposta` ASC, `id_Composta` ASC), 
  INDEX `id_Composta` (`id_Composta` ASC), 
  CONSTRAINT `componentecomposta_ibfk_1`
    FOREIGN KEY (`id_ComponenteDeComposta`)
    REFERENCES `bd_ipc`.`descomponentecomposta` (`id_ComponenteDeComposta`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `componentecomposta_ibfk_2`
    FOREIGN KEY (`id_Composta`)
    REFERENCES `bd_ipc`.`composta` (`id_Composta`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `bd_ipc`.`proyectos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_ipc`.`proyectos` (
  `id_Proyecto` INT NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_Proyecto`)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `bd_ipc`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_ipc`.`usuario` (
  `id_Usuario` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `ApellidoPaterno` VARCHAR(20) NOT NULL,
  `ApellidoMaterno` VARCHAR(20) NOT NULL,
  `Telefono` VARCHAR(15) NOT NULL,
  `CorreoElectronico` VARCHAR(100) NOT NULL,
  `Contrasenia` VARCHAR(128) NOT NULL,
  `Foto` VARCHAR(150) NULL,
   `TipoUsuario` ENUM('isAdmin','isSuscrito','isParticipant'), 
  PRIMARY KEY (`id_Usuario`),
  UNIQUE INDEX `CorreoElectronico_UNIQUE` (`CorreoElectronico` ASC) 
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `bd_ipc`.`ctrlcomponentes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_ipc`.`ctrlcomponentes` (
  `id_Identificador` INT NOT NULL AUTO_INCREMENT,
  `id_Proyecto` INT NOT NULL,
  `id_Componente` INT NOT NULL,
  `bluetooth` VARCHAR(45) NULL DEFAULT NULL,  
  `id_Usuario` INT NOT NULL,
  `fechaIniResponsable` DATETIME NOT NULL,
  `fechaFinResponsable` DATETIME NOT NULL,
  PRIMARY KEY (`id_Identificador`),
  INDEX `id_Proyecto` (`id_Proyecto` ASC), 
  INDEX `id_Componente` (`id_Componente` ASC), 
  INDEX `bluetooth` (`bluetooth` ASC), 
  INDEX `id_Usuario` (`id_Usuario` ASC), 
  CONSTRAINT `ctrlcomponentes_ibfk_1`
    FOREIGN KEY (`id_Proyecto`)
    REFERENCES `bd_ipc`.`proyectos` (`id_Proyecto`)
    ON UPDATE CASCADE,
  CONSTRAINT `ctrlcomponentes_ibfk_2`
    FOREIGN KEY (`id_Componente`)
    REFERENCES `bd_ipc`.`catcomponentes` (`id_Componente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `ctrlcomponentes_ibfk_3`
    FOREIGN KEY (`bluetooth`)
    REFERENCES `bd_ipc`.`circuito` (`bluetooth`)
    ON UPDATE CASCADE,
  CONSTRAINT `ctrlcomponentes_ibfk_4`
    FOREIGN KEY (`id_Usuario`)
    REFERENCES `bd_ipc`.`usuario` (`id_Usuario`)
    ON UPDATE CASCADE
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `bd_ipc`.`material`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_ipc`.`material` (
  `id_Material` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Descripcion` VARCHAR(550) NULL DEFAULT NULL,
  PRIMARY KEY (`id_Material`),
  UNIQUE INDEX `Nombre` (`Nombre` ASC) 
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `bd_ipc`.`electrodos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_ipc`.`electrodos` (
  `id_Electrodos` INT NOT NULL AUTO_INCREMENT,
  `id_Material` INT NOT NULL,
  `Forma` VARCHAR(45) NOT NULL,
  `Largo` VARCHAR(45) NOT NULL,
  `Ancho` VARCHAR(45) NOT NULL,
  `Calibre_Cable` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_Electrodos`),
  INDEX `id_Material` (`id_Material` ASC), 
  CONSTRAINT `electrodos_ibfk_1`
    FOREIGN KEY (`id_Material`)
    REFERENCES `bd_ipc`.`material` (`id_Material`)
    ON UPDATE CASCADE
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `bd_ipc`.`sensadoSuelo`  
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_ipc`.`sensadoSuelo` (
  `bluetooth` VARCHAR(45) NOT NULL,  
  `fechaSensado` DATETIME NOT NULL,
  `Voltaje` FLOAT NOT NULL,
  `Amperaje` FLOAT NOT NULL,
  `PhSuelo` VARCHAR(45) NULL,
  `HumedadSuelo` FLOAT NULL,
  `id_PlantaIndividuo` INT NOT NULL, 
  PRIMARY KEY (`bluetooth`, `fechaSensado`),
  INDEX `id_Suelo` (`id_Suelo` ASC), 
  INDEX `fk_sensadoSuelo_plantaindividuo1_idx` (`id_PlantaIndividuo` ASC), 
  CONSTRAINT `energiaplanta_ibfk_1`
    FOREIGN KEY (`bluetooth`)
    REFERENCES `bd_ipc`.`circuito` (`bluetooth`)
    ON UPDATE CASCADE,
  CONSTRAINT `energiaplanta_ibfk_3`
    FOREIGN KEY (`id_Suelo`)
    REFERENCES `bd_ipc`.`suelo` (`id_Suelo`)
    ON UPDATE CASCADE,
  CONSTRAINT `fk_sensadoSuelo_plantaindividuo1`
    FOREIGN KEY (`id_PlantaIndividuo`)
    REFERENCES `bd_ipc`.`plantaindividuo` (`id_PlantaIndividuo`)
    ON DELETE SET NULL
    ON UPDATE CASCADE
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `bd_ipc`.`video`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_ipc`.`video` (
  `id_Video` INT NOT NULL AUTO_INCREMENT,
  `Direccion` VARCHAR(150) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_Video`),
  UNIQUE INDEX `Nombre` (`Nombre` ASC) 
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `bd_ipc`.`tipoestimulacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_ipc`.`tipoestimulacion` (
  `id_TipoEstimulacion` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(30) NOT NULL,
  `Descripcion` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_TipoEstimulacion`),
  UNIQUE INDEX `Nombre` (`Nombre` ASC) 
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `bd_ipc`.`partesdeplanta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_ipc`.`partesdeplanta` (
  `id_PartePlanta` INT NOT NULL AUTO_INCREMENT,
  `Nombre_Cientifico` VARCHAR(45) NOT NULL,
  `Alias` VARCHAR(45) NULL DEFAULT NULL,
  `Descripcion` VARCHAR(150) NULL DEFAULT NULL,
  `Foto` VARCHAR(150) NULL, 
  PRIMARY KEY (`id_PartePlanta`),
  UNIQUE INDEX `Nombre_Cientifico` (`Nombre_Cientifico` ASC) 
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `bd_ipc`.`experimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_ipc`.`experimento` (
  `id_Experimento` INT NOT NULL AUTO_INCREMENT,
  `id_TipoEstimulacion` INT NOT NULL,
  `id_PartePlanta` INT NULL,
  `Fecha_Sensado` DATE NOT NULL,
  `Hora_inicio` DATETIME NOT NULL,
  `Hora_fin` DATETIME NOT NULL,
  `id_PlantaIndividuo` INT NOT NULL,
  `id_Electrodos` INT NOT NULL,
  `bluetooth` VARCHAR(45) NOT NULL,  
  `id_Video` INT NOT NULL,
  `id_Usuario` INT NOT NULL,
  `id_espacios` INT NOT NULL,
  `id_plaga` INT NULL, 
  PRIMARY KEY (`id_Experimento`),
  INDEX `id_Usuario` (`id_Usuario` ASC), 
  INDEX `id_PlantaIndividuo` (`id_PlantaIndividuo` ASC), 
  INDEX `id_Electrodos` (`id_Electrodos` ASC), 
  INDEX `id_Video` (`id_Video` ASC), 
  INDEX `bluetooth` (`bluetooth` ASC), 
  INDEX `id_TipoEstimulacion` (`id_TipoEstimulacion` ASC), 
  INDEX `id_PartePlanta` (`id_PartePlanta` ASC), 
  INDEX `id_espacios` (`id_espacios` ASC),
  INDEX `fk_experimento_plagas_idx` (`id_plaga` ASC), 
  CONSTRAINT `experimento_ibfk_1`
    FOREIGN KEY (`id_Usuario`)
    REFERENCES `bd_ipc`.`usuario` (`id_Usuario`)
    ON UPDATE CASCADE,
  CONSTRAINT `experimento_ibfk_2`
    FOREIGN KEY (`id_PlantaIndividuo`)
    REFERENCES `bd_ipc`.`plantainindividuo` (`id_PlantaIndividuo`)
    ON UPDATE CASCADE,
  CONSTRAINT `experimento_ibfk_3`
    FOREIGN KEY (`id_Electrodos`)
    REFERENCES `bd_ipc`.`electrodos` (`id_Electrodos`)
    ON UPDATE CASCADE,
  CONSTRAINT `experimento_ibfk_4`
    FOREIGN KEY (`id_Video`)
    REFERENCES `bd_ipc`.`video` (`id_Video`)
    ON UPDATE CASCADE,
  CONSTRAINT `experimento_ibfk_5`
    FOREIGN KEY (`bluetooth`)
    REFERENCES `bd_ipc`.`circuito` (`bluetooth`)
    ON UPDATE CASCADE,
  CONSTRAINT `experimento_ibfk_6`
    FOREIGN KEY (`id_TipoEstimulacion`)
    REFERENCES `bd_ipc`.`tipoestimulacion` (`id_TipoEstimulacion`)
    ON UPDATE CASCADE,
  CONSTRAINT `experimento_ibfk_7`
    FOREIGN KEY (`id_PartePlanta`)
    REFERENCES `bd_ipc`.`partesdeplanta` (`id_PartePlanta`)
    ON UPDATE CASCADE,
  CONSTRAINT `experimento_ibfk_8`
    FOREIGN KEY (`id_espacios`)
    REFERENCES `bd_ipc`.`espacios` (`id_espacios`)
    ON UPDATE CASCADE,
  CONSTRAINT `fk_experimento_plagas` 
    FOREIGN KEY (`id_plaga`)
    REFERENCES `bd_ipc`.`plagas` (`id_Plaga`)
    ON DELETE SET NULL
    ON UPDATE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET=utf8mb4;


-- -----------------------------------------------------
-- Table `bd_ipc`.`experimentoDifPot`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_ipc`.`experimentoDifPot` (
  `id_Experimento` INT NOT NULL,
  `Fecha_sensado` DATETIME NOT NULL,
  `Hora` TIME NOT NULL,
  `DifPot` FLOAT NOT NULL,
  `distancia` FLOAT NULL, 
  PRIMARY KEY (`id_Experimento`, `Fecha_sensado`, `Hora`),
  CONSTRAINT `fk_experimentoDifPot_experimento`
    FOREIGN KEY (`id_Experimento`)
    REFERENCES `bd_ipc`.`experimento` (`id_Experimento`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `bd_ipc`.`plantapartes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_ipc`.`plantapartes` (
  `id_PartePlanta` INT NOT NULL,
  `id_Planta` INT NOT NULL,
  UNIQUE INDEX `id_Planta` (`id_Planta` ASC, `id_PartePlanta` ASC), 
  INDEX `id_PartePlanta` (`id_PartePlanta` ASC), 
  CONSTRAINT `plantapartes_ibfk_1`
    FOREIGN KEY (`id_PartePlanta`)
    REFERENCES `bd_ipc`.`partesdeplanta` (`id_PartePlanta`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `plantapartes_ibfk_2`
    FOREIGN KEY (`id_Planta`)
    REFERENCES `bd_ipc`.`plantas` (`id_Planta`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `bd_ipc`.`proyectocomponentes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_ipc`.`proyectocomponentes` (
  `id_Proyecto` INT NOT NULL,
  `id_Componente` INT NOT NULL,
  `Cantidad` INT NOT NULL,
  `Observaciones` VARCHAR(45) NOT NULL, 
  UNIQUE INDEX `id_Proyecto` (`id_Proyecto` ASC, `id_Componente` ASC), 
  INDEX `id_Componente` (`id_Componente` ASC), 
  CONSTRAINT `proyectocomponentes_ibfk_1`
    FOREIGN KEY (`id_Componente`)
    REFERENCES `bd_ipc`.`catcomponentes` (`id_Componente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `proyectocomponentes_ibfk_2`
    FOREIGN KEY (`id_Proyecto`)
    REFERENCES `bd_ipc`.`proyectos` (`id_Proyecto`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `bd_ipc`.`sensadoambiental`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_ipc`.`sensadoambiental` (
  `FechaSensado` DATETIME NOT NULL,
  `TempAmbiental` FLOAT NULL DEFAULT NULL,
  `Humedad` FLOAT NULL DEFAULT NULL,
  `Lux` FLOAT NULL DEFAULT NULL,
  `Radiacion` FLOAT NULL DEFAULT NULL,
  `bluetooth` VARCHAR(45) NOT NULL,  
  `Voltaje` FLOAT NULL,
  `Amperaje` FLOAT NULL,
  `Luz_Azul` FLOAT,
  `Luz_Blanca` FLOAT,
  `Luz_Roja` FLOAT, 
  INDEX `bluetooth` (`bluetooth` ASC), 
  CONSTRAINT `sensadoambiental_ibfk_2`
    FOREIGN KEY (`bluetooth`)
    REFERENCES `bd_ipc`.`circuito` (`bluetooth`)
    ON UPDATE CASCADE
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `bd_ipc`.`sensadocontaminantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_ipc`.`sensadocontaminantes` (
  `bluetooth` VARCHAR(45) NOT NULL,  
  `fechaSensado` DATETIME NOT NULL,
  `CO` DECIMAL(5,2) NOT NULL,
  `CO2` DECIMAL(5,2) NOT NULL,
  `O` DECIMAL(5,2) NOT NULL,
  `COVs` DECIMAL(5,2) NOT NULL, 
  PRIMARY KEY (`fechaSensado`),
  INDEX `bluetooth` (`bluetooth` ASC), 
  CONSTRAINT `sensadocontaminantes_ibfk_1`
    FOREIGN KEY (`bluetooth`)
    REFERENCES `bd_ipc`.`circuito` (`bluetooth`)
    ON UPDATE CASCADE
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `bd_ipc`.`suelocomposta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_ipc`.`suelocomposta` (
  `id_Suelo` INT NOT NULL,
  `id_Composta` INT NOT NULL, 
  UNIQUE INDEX `id_Suelo` (`id_Suelo` ASC, `id_Composta` ASC), 
  INDEX `id_Composta` (`id_Composta` ASC), 
  CONSTRAINT `suelocomposta_ibfk_1`
    FOREIGN KEY (`id_Suelo`)
    REFERENCES `bd_ipc`.`suelo` (`id_Suelo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `suelocomposta_ibfk_2`
    FOREIGN KEY (`id_Composta`)
    REFERENCES `bd_ipc`.`composta` (`id_Composta`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `bd_ipc`.`especies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_ipc`.`especies` (
  `id_especies` INT NOT NULL AUTO_INCREMENT,
  `Nombre_Cientifico` VARCHAR(45) NULL,
  `Alias` VARCHAR(45) NULL,
  `Foto` VARCHAR(150) NULL,
  `Descripcion` VARCHAR(150) NULL,
  `Origen` VARCHAR(45) NULL,
  `id_Planta` INT NOT NULL, 
  PRIMARY KEY (`id_especies`),
  INDEX `fk_especies_plantas1_idx` (`id_Planta` ASC), 
  CONSTRAINT `fk_especies_plantas1`
    FOREIGN KEY (`id_Planta`)
    REFERENCES `bd_ipc`.`plantas` (`id_Planta`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4; 


-- -----------------------------------------------------
-- Table `bd_ipc`.`tokens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_ipc`.`tokens` (
  `id_tokens` INT NOT NULL AUTO_INCREMENT,
  `token` VARCHAR(128) NULL,
  `id_Usuario` INT NOT NULL, 
  PRIMARY KEY (`id_tokens`),
  INDEX `fk_tokens_usuario1_idx` (`id_Usuario` ASC), 
  CONSTRAINT `fk_tokens_usuario1`
    FOREIGN KEY (`id_Usuario`)
    REFERENCES `bd_ipc`.`usuario` (`id_Usuario`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4; 


-- -----------------------------------------------------
-- Table `bd_ipc`.`espaciosUsuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_ipc`.`espaciosUsuarios` (
  `id_Usuario` INT NOT NULL,
  `id_espacios` INT NOT NULL,
  `isAdminEspacio` TINYINT NOT NULL DEFAULT 0, 
  PRIMARY KEY (`id_Usuario`, `id_espacios`),
  INDEX `fk_espaciosUsuarios_espacios1_idx` (`id_espacios` ASC), 
  CONSTRAINT `fk_espaciosUsuarios_espacios1`
    FOREIGN KEY (`id_espacios`)
    REFERENCES `bd_ipc`.`espacios` (`id_espacios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_espaciosUsuarios_usuario1`
    FOREIGN KEY (`id_Usuario`)
    REFERENCES `bd_ipc`.`usuario` (`id_Usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4; 


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;