# Generated by Django 4.2.27 on 2026-02-11 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circuito',
            fields=[
                ('bluetooth', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('id_tipo_circuito', models.IntegerField()),
                ('id_espacios', models.IntegerField()),
            ],
            options={
                'db_table': 'circuito',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SensadoAmbiental',
            fields=[
                ('FechaSensado', models.DateTimeField(primary_key=True, serialize=False)),
                ('TempAmbiental', models.FloatField(null=True)),
                ('Humedad', models.FloatField(null=True)),
                ('Lux', models.FloatField(null=True)),
                ('Radiacion', models.FloatField(null=True)),
                ('bluetooth', models.IntegerField()),
                ('Voltaje', models.FloatField(null=True)),
                ('Amperaje', models.FloatField(null=True)),
                ('Luz_Azul', models.FloatField(null=True)),
                ('Luz_Blanca', models.FloatField(null=True)),
                ('Luz_Roja', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'sensadoambiental',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SensadoContaminantes',
            fields=[
                ('fechaSensado', models.DateTimeField(primary_key=True, serialize=False)),
                ('CO', models.DecimalField(decimal_places=2, max_digits=5)),
                ('CO2', models.DecimalField(decimal_places=2, max_digits=5)),
                ('O', models.DecimalField(decimal_places=2, max_digits=5)),
                ('COVs', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'sensadocontaminantes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='sensadoSuelo',
            fields=[
                ('id_EnergiaPlanta', models.AutoField(primary_key=True, serialize=False)),
                ('bluetooth', models.IntegerField()),
                ('fechaSensado', models.DateTimeField()),
                ('Voltaje', models.FloatField()),
                ('Amperaje', models.FloatField()),
                ('PhSuelo', models.CharField(blank=True, max_length=45, null=True)),
                ('HumedadSuelo', models.FloatField(blank=True, null=True)),
                ('id_PlantaIndividuo', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sensadoSuelo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Suelo',
            fields=[
                ('id_Suelo', models.AutoField(primary_key=True, serialize=False)),
                ('CP', models.IntegerField()),
                ('Nombre_Cientifico', models.CharField(max_length=45, null=True)),
                ('Descripcion', models.CharField(max_length=45, null=True)),
            ],
            options={
                'db_table': 'suelo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoCircuito',
            fields=[
                ('id_tipo_circuito', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
    ]
