# Generated by Django 4.2.27 on 2026-02-11 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0003_remove_tokenusuario_id_tokenusuario_id_tokens_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EspaciosUsuarios',
            fields=[
                ('id_usuario', models.ForeignKey(db_column='id_Usuario', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='usuarios.usuario')),
                ('isAdminEspacio', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'espaciosUsuarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlantaPartes',
            fields=[
                ('id_parteplanta', models.IntegerField(db_column='id_PartePlanta', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'plantapartes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Espacio',
            fields=[
                ('id_espacios', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_espacio', models.CharField(blank=True, max_length=45)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='espacios/')),
                ('clave_acceso', models.CharField(blank=True, max_length=45)),
                ('usuarios_miembros', models.ManyToManyField(related_name='usuarios_miembros', through='plantas.EspaciosUsuarios', to='usuarios.usuario')),
            ],
            options={
                'db_table': 'espacios',
            },
        ),
        migrations.CreateModel(
            name='PartePlanta',
            fields=[
                ('nombre_cientifico', models.CharField(blank=True, max_length=45)),
                ('alias', models.CharField(blank=True, max_length=45)),
                ('descripcion', models.CharField(blank=True, max_length=300)),
                ('id_PartePlanta', models.AutoField(primary_key=True, serialize=False)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='partes/')),
            ],
            options={
                'db_table': 'partesdeplanta',
            },
        ),
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('nombre_cientifico', models.CharField(blank=True, max_length=45)),
                ('alias', models.CharField(blank=True, max_length=45)),
                ('descripcion', models.CharField(blank=True, max_length=300)),
                ('id_planta', models.AutoField(primary_key=True, serialize=False)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='plantas/')),
                ('familia', models.CharField(blank=True, max_length=45)),
            ],
            options={
                'db_table': 'plantas',
            },
        ),
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('nombre_cientifico', models.CharField(blank=True, max_length=45)),
                ('alias', models.CharField(blank=True, max_length=45)),
                ('descripcion', models.CharField(blank=True, max_length=300)),
                ('id_especies', models.AutoField(primary_key=True, serialize=False)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='especies/')),
                ('origen', models.CharField(blank=True, max_length=45)),
                ('id_Planta', models.ForeignKey(blank=True, db_column='id_Planta', null=True, on_delete=django.db.models.deletion.CASCADE, to='plantas.planta')),
            ],
            options={
                'db_table': 'especies',
            },
        ),
        migrations.CreateModel(
            name='PlantasEspacios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('id_Planta', models.ForeignKey(db_column='id_Planta', on_delete=django.db.models.deletion.CASCADE, related_name='rel_espacios', to='plantas.planta')),
                ('id_espacio', models.ForeignKey(db_column='id_espacio', on_delete=django.db.models.deletion.CASCADE, related_name='rel_plantas', to='plantas.espacio')),
            ],
            options={
                'db_table': 'plantasespacios',
                'unique_together': {('id_Planta', 'id_espacio')},
            },
        ),
    ]
