# Generated by Django 4.2.27 on 2026-02-12 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='plantasespacios',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='especie',
            name='id_Planta',
        ),
        migrations.AddField(
            model_name='especie',
            name='plantas',
            field=models.ManyToManyField(blank=True, related_name='especies', to='plantas.planta'),
        ),
        migrations.AddField(
            model_name='plantasespacios',
            name='plantas_relacionadas',
            field=models.ManyToManyField(blank=True, to='plantas.planta'),
        ),
        migrations.RemoveField(
            model_name='plantasespacios',
            name='id_Planta',
        ),
    ]
