# Generated by Django 4.2.27 on 2026-02-13 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0002_alter_plantasespacios_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='espacio',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='especie',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='parteplanta',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='planta',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='plantasespacios',
            options={'managed': False},
        ),
    ]
