# Generated by Django 4.2.20 on 2025-06-08 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_Usuario', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=45)),
                ('ApellidoPaterno', models.CharField(max_length=20)),
                ('ApellidoMaterno', models.CharField(max_length=20)),
                ('Telefono', models.CharField(max_length=15)),
                ('CorreoElectronico', models.CharField(max_length=100, unique=True)),
                ('Contrasenia', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='TokenUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=128, unique=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
        ),
    ]
