# Generated by Django 4.2.20 on 2025-06-08 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tokenusuario',
            table='tokens',
        ),
    ]
