<<<<<<< HEAD
# Generated by Django 4.2.27 on 2026-02-23 21:09
=======
# Generated by Django 4.2.27 on 2026-02-11 05:28
>>>>>>> master

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_tokenusuario_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tokenusuario',
            name='id',
        ),
        migrations.AddField(
            model_name='tokenusuario',
            name='id_tokens',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='Foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_perfil_usuarios/'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='TipoUsuario',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tokenusuario',
            name='usuario',
            field=models.OneToOneField(db_column='id_Usuario', on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario'),
        ),
    ]
