# Generated by Django 4.2.20 on 2025-03-18 04:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enfermedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('sintomas', models.TextField(blank=True)),
                ('tratamiento', models.TextField(blank=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='enfermedades/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('origen', models.CharField(max_length=20)),
                ('descubridor', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Plaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('sintomas', models.TextField(blank=True)),
                ('tratamiento', models.TextField(blank=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='plagas/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='plantas/')),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plantas', to='plantas.especie')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
