# Generated by Django 4.2.27 on 2026-02-11 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monitoreo', '0001_initial'),
        ('plantas', '0001_initial'),
        ('usuarios', '0003_remove_tokenusuario_id_tokenusuario_id_tokens_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Electrodos',
            fields=[
                ('id_electrodos', models.AutoField(primary_key=True, serialize=False)),
                ('forma', models.CharField(max_length=45)),
                ('largo', models.CharField(max_length=45)),
                ('ancho', models.CharField(max_length=45)),
                ('calibre_cable', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'electrodos',
            },
        ),
        migrations.CreateModel(
            name='EtapaDesarrollo',
            fields=[
                ('id_etapa', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cientifico', models.CharField(blank=True, max_length=45)),
                ('alias', models.CharField(blank=True, max_length=45)),
            ],
            options={
                'db_table': 'etapadesarrollo',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id_material', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=45)),
                ('descripcion', models.CharField(blank=True, max_length=550)),
            ],
            options={
                'db_table': 'material',
            },
        ),
        migrations.CreateModel(
            name='OrigenCrianza',
            fields=[
                ('id_OrigenCrianza', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=45)),
                ('descripcion', models.CharField(blank=True, max_length=550)),
            ],
            options={
                'db_table': 'origencrianzaplanta',
            },
        ),
        migrations.CreateModel(
            name='Plagas',
            fields=[
                ('id_plaga', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cientifico', models.CharField(blank=True, max_length=45)),
                ('alias', models.CharField(blank=True, max_length=45)),
                ('descripcion', models.CharField(blank=True, max_length=150)),
                ('tratamiento', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'db_table': 'plagas',
            },
        ),
        migrations.CreateModel(
            name='Tacto',
            fields=[
                ('id_tipotacto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=15)),
                ('descripcion', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoEstimulacion',
            fields=[
                ('id_TipoEstimulacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=20)),
                ('descripcion', models.CharField(blank=True, max_length=45)),
            ],
            options={
                'db_table': 'tipoestimulacion',
            },
        ),
        migrations.CreateModel(
            name='Ubicaciones',
            fields=[
                ('cp', models.IntegerField(primary_key=True, serialize=False)),
                ('estado', models.CharField(blank=True, max_length=45)),
                ('municipio', models.CharField(blank=True, max_length=45)),
                ('colonia', models.CharField(blank=True, max_length=45)),
            ],
            options={
                'db_table': 'ubicaciones',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id_Video', models.AutoField(primary_key=True, serialize=False)),
                ('Direccion', models.CharField(blank=True, max_length=150)),
                ('Nombre', models.CharField(blank=True, max_length=45)),
            ],
            options={
                'db_table': 'video',
            },
        ),
        migrations.CreateModel(
            name='Suelo',
            fields=[
                ('id_suelo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cientifico', models.CharField(blank=True, max_length=45)),
                ('descripcion', models.CharField(blank=True, max_length=45)),
                ('cp', models.ForeignKey(db_column='CP', on_delete=django.db.models.deletion.CASCADE, to='experimentos.ubicaciones')),
            ],
            options={
                'db_table': 'suelo',
            },
        ),
        migrations.CreateModel(
            name='PlantaIndividuo',
            fields=[
                ('id_PlantaIndividuo', models.AutoField(primary_key=True, serialize=False)),
                ('id_OrigenCrianza', models.ForeignKey(db_column='id_OrigenCrianza', on_delete=django.db.models.deletion.CASCADE, to='experimentos.origencrianza')),
                ('id_espacios', models.ForeignKey(db_column='id_espacios', on_delete=django.db.models.deletion.CASCADE, to='plantas.espacio')),
                ('id_etapa', models.ForeignKey(db_column='id_Etapa', on_delete=django.db.models.deletion.CASCADE, to='experimentos.etapadesarrollo')),
                ('id_planta', models.ForeignKey(db_column='id_Planta', on_delete=django.db.models.deletion.CASCADE, to='plantas.planta')),
                ('id_suelo', models.ForeignKey(db_column='id_Suelo', on_delete=django.db.models.deletion.CASCADE, to='experimentos.suelo')),
                ('plagas_id_Plaga', models.ForeignKey(db_column='plagas_id_Plaga', on_delete=django.db.models.deletion.CASCADE, to='experimentos.plagas')),
            ],
            options={
                'db_table': 'plantaindividuo',
            },
        ),
        migrations.CreateModel(
            name='Experimento',
            fields=[
                ('id_Experimento', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha_Sensado', models.DateField()),
                ('Hora_inicio', models.DateTimeField()),
                ('Hora_fin', models.DateTimeField()),
                ('Distancia', models.FloatField()),
                ('bluetooth', models.ForeignKey(db_column='bluetooth', on_delete=django.db.models.deletion.CASCADE, to='monitoreo.circuito')),
                ('id_Electrodos', models.ForeignKey(db_column='id_electrodos', on_delete=django.db.models.deletion.CASCADE, to='experimentos.electrodos')),
                ('id_PartePlanta', models.ForeignKey(db_column='id_PartePlanta', on_delete=django.db.models.deletion.CASCADE, to='plantas.parteplanta')),
                ('id_PlantaIndividuo', models.ForeignKey(db_column='id_PlantaIndividuo', on_delete=django.db.models.deletion.CASCADE, to='experimentos.plantaindividuo')),
                ('id_TipoEstimulacion', models.ForeignKey(db_column='id_TipoEstimulacion', on_delete=django.db.models.deletion.CASCADE, to='experimentos.tipoestimulacion')),
                ('id_Usuario', models.ForeignKey(db_column='id_Usuario', on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
                ('id_Video', models.ForeignKey(db_column='id_Video', on_delete=django.db.models.deletion.CASCADE, to='experimentos.video')),
                ('id_espacios', models.ForeignKey(db_column='id_espacios', on_delete=django.db.models.deletion.CASCADE, to='plantas.espacio')),
            ],
            options={
                'db_table': 'experimento',
            },
        ),
        migrations.AddField(
            model_name='electrodos',
            name='id_material',
            field=models.ForeignKey(db_column='id_Material', on_delete=django.db.models.deletion.CASCADE, to='experimentos.material'),
        ),
    ]
